name: Release to NPM
'on':
  push:
    tags:
      - v*
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0
      - name: Setup Node.js - 14.x.x
        uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f
        with:
          node-version: '>=14.18'
          cache: npm
      - uses: actions/cache@v2
        name: Cache Node Modules
        with:
          path: ~/.npm
          key: ${{ runner.os}}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Node modules
        run: npm ci
      - name: Run tests
        run: npm run test
  publish:
    name: Release to NPM registry
    needs:
      - test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          fetch-depth: 0
      - name: Setup Node.js - 14.x.x
        uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f
        with:
          node-version: '>=14.18'
          cache: npm
      - uses: actions/cache@v2
        name: Cache Node Modules
        with:
          path: ~/.npm
          key: ${{ runner.os}}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install Node modules
        run: npm ci
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://registry.npmjs.org/
      - name: Publish to GitHub
        uses: JS-DevTools/npm-publish@0f451a94170d1699fd50710966d48fb26194d939
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: https://npm.pkg.github.com
